module.exports = {
  morgana: ["轮子妈", "轮妈"],
  masteryi: ["剑圣"],
  vayne: ["vn", "薇恩"],
  graves: ["男枪"],
  missfortune: ["女枪", "mf", "赏金"],
  caitlyn: ["女警"],
  leesin: ["瞎子", "盲僧", "李青"],
  tryndamere: ["蛮王"],
  darius: ["诺手"],
  garen: ["德玛", "大宝剑"],
  jarvaniv: ["皇子", "j4"],
  alistar: ["牛头"],
  blitzcrank: ["机器人"],
  nautilus: ["泰坦", "大鱼人"],
  fizz: ["小鱼人"],
  annie: ["火女"],
  brand: ["火男"],
  lissandra: ["冰女"],
  anivia: ["冰鸟", "凤凰"],
  leona: ["日女"],
  sona: ["琴女"],
  janna: ["风女"],
  karma: ["扇子妈"],
  soraka: ["奶妈", "星妈"],
  leblanc: ["妖姬"],
  katarina: ["卡特"],
  talon: ["男刀"],
  irelia: ["刀妹"],
  fiora: ["剑姬"],
  aatrox: ["剑魔"],
  yasuo: ["风男", "快乐风男", "剑豪"],
  yone: ["兄贵"],
  riven: ["锐雯"],
  jax: ["武器"],
  xinzhao: ["赵信", "德邦"],
  monkeyking: ["猴子", "悟空"],
  vi: ["拳女"],
  lucian: ["奥巴马"],
  ezreal: ["ez", "伊泽"],
  twistedfate: ["卡牌", "tf"],
  ashe: ["寒冰", "爱射"],
  ahri: ["狐狸"],
  jinx: ["爆爆"],
  khazix: ["螳螂"],
  elise: ["蜘蛛"],
  renekton: ["鳄鱼"],
  nasus: ["狗头"],
  malphite: ["石头人", "石头"],
  maokai: ["大树"],
  hecarim: ["人马"],
  shyvana: ["龙女"],
  aurelionsol: ["龙王"],
  evelynn: ["寡妇"],
  reksai: ["挖掘机"],
  tahmkench: ["蛤蟆"],
  kalista: ["滑板鞋"],
  twitch: ["老鼠"],
  kogmaw: ["大嘴"],
  karthus: ["死歌"],
  veigar: ["小法"],
  cassiopeia: ["蛇女"],
  syndra: ["球女"],
  orianna: ["发条"],
  nidalee: ["豹女"],
  gangplank: ["船长"],
  kayle: ["大天使"],
  zed: ["儿童劫"],
  kayn: ["红凯", "蓝凯"],
  vladimir: ["吸血鬼"],
  warwick: ["狼人"],
  volibear: ["狗熊"],
  kennen: ["电耗子"],
  rengar: ["狮子狗"],
  yorick: ["掘墓"],
  camille: ["腿女"],
  aphelios: ["月男"],
  lillia: ["小鹿"],
  neeko: ["变色龙"],
  hwei: ["画家"],
  mordekaiser: ["铁男"],
  urgot: ["螃蟹"],
  tristana: ["小炮"],
  corki: ["飞机"],
  heimerdinger: ["大头"],
  fiddlesticks: ["稻草人"],
  viktor: ["三只手"],
  ryze: ["光头"],
  chogath: ["大虫子"],
  velkoz: ["大眼"],
  malzahar: ["蚂蚱"],
  skarner: ["蝎子"],
  swain: ["乌鸦"],
  sejuani: ["猪妹"],
  nunu: ["雪人"],
  taric: ["宝石"],
  illaoi: ["触手妈"],
  amumu: ["木乃伊"],
  nocturne: ["梦魇"],
  gragas: ["酒桶"],
  singed: ["炼金"],
  drmundo: ["蒙多"],
  poppy: ["波比"],
  quinn: ["鸟人"],
  azir: ["沙皇", "皇帝"],
  nami: ["美人鱼"],
  yuumi: ["猫咪"],
  gwen: ["剪妹"],
  viego: ["破败"],
  smolder: ["小龙"],
  ziggs: ["炸弹人"],
  braum: ["布隆"],
  thresh: ["锤石"],
  kaisa: ["卡莎"],
  varus: ["维鲁斯"],
  sivir: ["轮子妈", "轮妈"],
  teemo: ["蘑菇"],
  shaco: ["小丑"],
  lux: ["光辉"],
  diana: ["皎月"],
  zoe: ["佐伊"],
  pyke: ["派克"],
  senna: ["赛娜"],
  sett: ["腕豪"],
  ambessa: ["狼母"],
  aurora: ["兔子"],
  belveth: ["虚空女皇"]
}
